apiVersion: deployments.plural.sh/v1alpha1
kind: AgentRuntime
metadata:
  name: test-claude-dind
  namespace: claude
spec:
  dind: true
  type: "CLAUDE"
  targetNamespace: "claude"
  config:
    claude:
      apiKeySecretRef:
        name: claude-api-key
        key: apiKey
  template:
    spec:
      containers:
      - name: default
        image: ghcr.io/pluralsh/agent-harness:0.6.17-claude-1.0.128
        args:
          - --v=3





