apiVersion: deployments.plural.sh/v1alpha1
kind: AgentRuntime
metadata:
  name: test-codex
  namespace: codex
spec:
  type: "CODEX"
  targetNamespace: "codex"
  config:
    claude:
      apiKeySecretRef:
        name: codex-api-key
        key: apiKey

