---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: deploymentaccesses.platform.plural.sh
spec:
  group: platform.plural.sh
  names:
    kind: DeploymentAccess
    listKind: DeploymentAccessList
    plural: deploymentaccesses
    singular: deploymentaccess
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              credentialsSecretName:
                description: CredentialsSecretName is the name of the secret that
                  operator should populate with the credentials. If a secret by this
                  name already exists, then it is assumed that credentials have already
                  been generated. It is not overridden. This secret is deleted when
                  the DeploymentAccess is delted.
                type: string
              deploymentAccessClassName:
                description: DeploymentAccessClassName is the name of the DeploymentAccessClass
                type: string
            required:
            - credentialsSecretName
            - deploymentAccessClassName
            type: object
          status:
            properties:
              accessGranted:
                description: AccessGranted indicates the successful grant of privileges
                  to access the bucket
                type: boolean
              accountID:
                description: AccountID is the unique ID for the account in the OSP.
                  It will be populated by the COSI sidecar once access has been successfully
                  granted.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
